### ISSUE TITLE
Неработоспособность TinyMCE

### ISSUE THREAD

**Issue by maxim-novikov** [profsoux/profsoux_ru#261]
Любые попытки "продвинутой" работы с TinyMCE из админки жестоко обрубаются, т.к. все попапы он вызывает с static.profsoux.ru, и они, по причинам безопасности, блокируются как вызов из другого домена.

![image](https://cloud.githubusercontent.com/assets/4518331/5710537/1d6c9312-9ab4-11e4-8719-7d3097105844.png)

Я что-то делаю не так?

**Comment by h4** [comment]
Access-control-allow-origin: *

понедельник, 12 января 2015 г. пользователь Maxim Novikov написал:

**Comment by maxim-novikov** [comment]
Не помогает, однако.

![image](https://cloud.githubusercontent.com/assets/4518331/5716818/7dbdb280-9b06-11e4-9836-187fe0d2a59b.png)

**Comment by h4** [comment]
Проверяйте.

**Comment by maxim-novikov** [comment]
Uncaught SecurityError: Blocked a frame with origin "http://static.profsoux.ru" from accessing a frame with origin "http://2015.profsoux.ru". The frame requesting access set "document.domain" to "profsoux.ru", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access.

**Comment by h4** [comment]
Кеш прочисти для 
http://static.profsoux.ru/grappelli/tinymce/jscripts/tiny_mce/tiny_mce_popup.js
http://static.profsoux.ru/grappelli/tinymce/jscripts/tiny_mce/tiny_mce.js

В этих файлах должно первой строчкой идти `document.domain = 'profsoux.ru';`

**Comment by maxim-novikov** [comment]
Всё, заработало. Кэш на статике у меня прочищен был, надо было кэш ориджина тоже прочистить.
