### ISSUE TITLE
Кэширование

### ISSUE THREAD

**Issue by maxim-novikov** [profsoux/profsoux_ru#262]
На данный момент сайт не форсит обновление кэша страниц по факту обновления контента через админку. Хорошо бы это поправить, если есть такая возможность.

**Comment by h4** [comment]
Вроде бы никакого механизма кеширования я специально не включал.

**Comment by maxim-novikov** [comment]
В настройках джанги я CACHES не нашёл, потому и написал.

Вообще в заголовках только и пишется что
Cache-Control: max-age=1209600

Но простой практический тест: 1) открыл страничку; 2) ушёл с странички; 3)
изменил страничку в админке; 4) снова пришёл на страничку - показывает, что
проблема есть. :(

В большинстве хитрых CMSок, с которыми я работал, были настройки кэша от
подобных вещей (ручные или автоматические), но тут я теряюсь. Пойду погуглю.


28 января 2015 г., 23:21 пользователь Mikhail Baranov <
notifications@github.com> написал:

**Comment by julvk** [comment]
Главное, что раньше такого не было :(

**Comment by maxim-novikov** [comment]
В общем и целом, всё что я понял из быстрого гугления:
- проблема не нова и не уникальна;
- тупой и простой способ решения сводится к установке декоратора
@cache_control(must_revalidate=True).

Мне осталось только узнать что такое декоратор и куда его ставить. :)

2015-01-28 23:35 GMT+03:00 Julia Kryuchkova (McCulloch) <
notifications@github.com>:

**Comment by maxim-novikov** [comment]
Миша, скажи пожалуйста, прав ли я в этом нагугленном решении:

1. Добавить в views.py
from django.views.decorators.cache import never_cache

2. Добавить в views.py перед каждым foo(request) строчку
@never_cache

?

Я сильно сомневаюсь во втором пункте...


28 января 2015 г., 23:43 пользователь Maxim Novikov <max.novikov@gmail.com>
написал:

**Comment by h4** [comment]
Нет, это плохое решение, когда надо отключить кеш на всём сайте.

Вообще, кеш похоже ставил nginx. Добавил в .htaccess отключение кеша на всём сайте.
```conf
FileETag None
<ifModule mod_headers.c>
     Header unset ETag
     Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
     Header set Pragma "no-cache"
     Header set Expires "Wed, 11 Jan 1984 05:00:00 GMT"
</ifModule>
```

**Comment by maxim-novikov** [comment]
Протестировано, работает, супер.
