### ISSUE TITLE
На хомяке разъезжается вёрстка в мобильной версии

### ISSUE THREAD

**Issue by julvk** [profsoux/profsoux_ru#263]
Что-то пошло не так в мобильной версии http://profsoux.ru/

**Comment by maxim-novikov** [comment]
Юль, а можно скриншот, чтобы понимать что именно не так?

**Comment by julvk** [comment]
Уменьши экран

**Comment by julvk** [comment]
http://zencoder.ru/%D1%80%D0%B5%D0%B6%D0%B8%D0%BC-%D1%8D%D0%BC%D1%83%D0%BB%D1%8F%D1%86%D0%B8%D0%B8-chrome/

**Comment by maxim-novikov** [comment]
![image](https://cloud.githubusercontent.com/assets/4518331/6148392/140fceea-b212-11e4-86e0-0f85db777737.png)
С эмуляцией сейчас попробую

**Comment by maxim-novikov** [comment]
На эмуляции (у меня) сбивается часть с контентом: заголовок и навигация работают нормально, футер, вроде бы, тоже. Буду посмотреть.

**Comment by maxim-novikov** [comment]
Вроде бы пофиксил. Посмотрите и закройте, плз, если всё ок.

**Comment by julvk** [comment]
Лучше, но не на много :( Тексты по-прежнему не влезают в экран, а если уменьшить масштаб - влезают, но становятся слишком мелкими, не читабельными.

**Comment by maxim-novikov** [comment]
Пофиксил разметку до 320 пикселей как минимум. Надеюсь, что станет лучше.

**Comment by julvk** [comment]
Да, проверили на iPhone5 и HTC 1S - нормально. Спасибо!
