### ISSUE TITLE
На англ. страничке исправить год, дату, подзаголовок

### ISSUE THREAD

**Issue by julvk** [profsoux/profsoux_ru#265]
На странице http://2015.profsoux.ru/eng/ при применении шаблона flatpages/en.html в шапке вылезает шаблон прошлого года: 

"ProfsoUX'14
User Experience conference
April 26, 2014. St. Petersburg, Russia"

Нужно заменить текст на новый (но чтобы на сайте прошлого года он не менялся).

Новый текст:

"ProfsoUX 15
#1 Conference For User Experience Specialists in Russia
April 25, 2015. Club House Centre, Saint Petersburg"

**Comment by maxim-novikov** [comment]
Ошибка, поехало во всех годах, будем фиксить

**Comment by maxim-novikov** [comment]
Fixed, please check

**Comment by julvk** [comment]
Кнопка регистрации ведёт незнамо куда

**Comment by julvk** [comment]
На англоязычной страничке 2014-го года в правой колонке - неправильная дата: "On 12/01/2013 the conference dedicated to usability and UX was held in Saint Petersburg"

**Comment by julvk** [comment]
На англ. страничке 2012-го и 2013-го года в правой колонке тоже ошибки в дате. И текст, что видео Coming soon - а они уже есть. Предлагаю на всех страничках прошлых лет сделать один текст. Сейчас придумаю, какой

**Comment by maxim-novikov** [comment]
Буду переписывать всё с нуля

**Comment by maxim-novikov** [comment]
Проблема с неверными датами решена. Жду единого текста.

**Comment by maxim-novikov** [comment]
Ссылка на регистрацию исправлена

**Comment by julvk** [comment]
Универсальный текст для прошлых конференций:

On (дата конфы) the great UX event was held in Saint Petersburg.

The Videos and Presentation slides can be found in the Speakers section (относительная ссылка на раздел /speakers/).

The Photos are at our Facebook group (ссылка на https://www.facebook.com/Profsoux/).

Many Thanks to our Guests, Partners (относительная ссылка на /partners/) and Volunteers (относительная ссылка на /organizers/)!

See you at the next ProfsoUX!

Кнопка регистрации, как сейчас.

**Comment by maxim-novikov** [comment]
Сделано.
